### ISSUE TITLE
Fixed?

### ISSUE THREAD

**Issue by djaax** [Vazerthon/node-monorepo-test#1]
Hi @Vazerthon,

I'm facing a very similar issue as you described in [this issue](https://github.com/emotion-js/emotion/issues/2192).

For me, the issue appeared after upgrading yarn (v1 -> v3) so I assume it has something to do with resolving the dependency correctly.

Were you able to figure out how to resolve your issue?

Thanks!

**Comment by Vazerthon** [comment]
Hey,
I'm afraid I didn't make any progress with it and ended up moving on to something else. This was a bit of a side project at work and I've now moved to another job.

Fwiw I've seen Yarn PnP being used with some success, maybe that could help you? https://next.yarnpkg.com/features/pnp

**Comment by djaax** [comment]
Alright, thanks for the quick reply. I'll have a look and will comment if I find a solution.

**Comment by djaax** [comment]
I ended up upgrading to Yarn with PnP which did not solve the problem in itself.

What solved my problem was removing all imports of `@emotion/css` in favor of `@emotion/react`.

I suspect, similar to having multiple `@emotion/react` instances as described in #2192, having conflicting `@emotion/css` and `@emotion/react` instances cause the emotion theme to not be passed correctly.

**Comment by Vazerthon** [comment]
Glad you found a way to fix it!
